### ISSUE TITLE
Download Latest X Builds Only

### ISSUE THREAD

**Issue by mattbocosoft** [Touchwonders/testflight-exporter#4]
We have many apps and thousands of builds per app. Could you add a command-line parameter that specifies how many latest builds to download for each app?

**Comment by fabiomassimo** [comment]
Yes, I think this is a good nice to have.
I'll put it on top of my features request.
Stay tuned.

**Comment by fabiomassimo** [comment]
Implemented in version [v0.2.1](https://github.com/Touchwonders/testflight-exporter/tree/v0.2.1)
